version: '2'
volumes:
  aula2-logs:
    external: true
services:
  aula2:
    image: oficina-docker:aula2-volumes
    build: .
    container_name: aula-2
    volumes: 
      - aula2-logs:/tmp
    restart: always


